function card(name, color, scryfallName, college = null, collegeColors = null) {
  return { name, color, scryfallName, college, collegeColors }
}

export const DECKS = {
  lorehold: {
    name: 'Lorehold Aggro',
    description: 'Red/White — aggressive forward momentum, recycle from discard',
    cards: [
      card('Illuminate History', 'red', 'Illuminate History', 'lorehold', ['white', 'red']),
      card('Lorehold Command', 'red', 'Lorehold Command', 'lorehold', ['white', 'red']),
      card('Velomachus Lorehold', 'red', 'Velomachus Lorehold', 'lorehold', ['white', 'red']),
      card('Hofri Ghostforge', 'red', 'Hofri Ghostforge', 'lorehold', ['white', 'red']),
      card('Silverquill Command', 'white', 'Silverquill Command', 'silverquill', ['white', 'black']),
      card('Killian, Ink Duelist', 'black', 'Killian, Ink Duelist', 'silverquill', ['white', 'black']),
      card('Lightning Bolt', 'red', 'Lightning Bolt'),
      card('Shock', 'red', 'Shock'),
      card('Dragon Mantle', 'red', 'Dragon Mantle'),
      card('Heartfire Immolator', 'red', 'Heartfire Immolator'),
      card('Fervent Champion', 'red', 'Fervent Champion'),
      card('Scorching Dragonfire', 'red', 'Scorching Dragonfire'),
      card('Storm-Kiln Artist', 'red', 'Storm-Kiln Artist'),
      card('Efreet Flamepainter', 'red', 'Efreet Flamepainter'),
      card('Academic Dispute', 'red', 'Academic Dispute'),
      card('Swords to Plowshares', 'white', 'Swords to Plowshares'),
      card('Elite Vanguard', 'white', 'Elite Vanguard'),
      card('Leonin Lightscribe', 'white', 'Leonin Lightscribe'),
      card('Clever Lumimancer', 'white', 'Clever Lumimancer'),
      card('Guiding Voice', 'white', 'Guiding Voice'),
      card('Star Pupil', 'white', 'Star Pupil'),
      card("Stonebinder's Familiar", 'white', "Stonebinder's Familiar"),
      card('Returned Pastcaller', 'white', 'Returned Pastcaller'),
      card('Pilgrim of the Ages', 'white', 'Pilgrim of the Ages'),
      card('Plains', 'colorless', 'Plains'),
      card('Plains', 'colorless', 'Plains'),
      card('Mountain', 'colorless', 'Mountain'),
      card('Mountain', 'colorless', 'Mountain'),
      card('Furycalm Snarl', 'colorless', 'Furycalm Snarl'),
      card('Lorehold Campus', 'colorless', 'Lorehold Campus'),
    ],
  },
  witherbloom: {
    name: 'Witherbloom Control',
    description: 'Green/Black — walls, traps, and board control',
    cards: [
      card('Witherbloom Command', 'green', 'Witherbloom Command', 'witherbloom', ['green', 'black']),
      card('Beledros Witherbloom', 'green', 'Beledros Witherbloom', 'witherbloom', ['green', 'black']),
      card('Dina, Soul Steeper', 'black', 'Dina, Soul Steeper', 'witherbloom', ['green', 'black']),
      card('Blex, Vexing Pest', 'green', 'Blex, Vexing Pest', 'witherbloom', ['green', 'black']),
      card('Quandrix Command', 'blue', 'Quandrix Command', 'quandrix', ['green', 'blue']),
      card('Zimone, Quandrix Prodigy', 'blue', 'Zimone, Quandrix Prodigy', 'quandrix', ['green', 'blue']),
      card('Overgrown Battlement', 'green', 'Overgrown Battlement'),
      card('Wall of Blossoms', 'green', 'Wall of Blossoms'),
      card('Dragonsguard Elite', 'green', 'Dragonsguard Elite'),
      card('Bookwurm', 'green', 'Bookwurm'),
      card('Mage Duel', 'green', 'Mage Duel'),
      card('Master Symmetrist', 'green', 'Master Symmetrist'),
      card('Bayou Groff', 'green', 'Bayou Groff'),
      card('Containment Breach', 'green', 'Containment Breach'),
      card('Emergent Sequence', 'green', 'Emergent Sequence'),
      card('Unwilling Ingredient', 'black', 'Unwilling Ingredient'),
      card('Lash of Malice', 'black', 'Lash of Malice'),
      card('Specter of the Fens', 'black', 'Specter of the Fens'),
      card('Eyetwitch', 'black', 'Eyetwitch'),
      card('Hunt for Specimens', 'black', 'Hunt for Specimens'),
      card('Plumb the Forbidden', 'black', 'Plumb the Forbidden'),
      card('Mage Hunter', 'black', 'Mage Hunter'),
      card('Brackish Trudge', 'black', 'Brackish Trudge'),
      card('Essence Infusion', 'black', 'Essence Infusion'),
      card('Swamp', 'colorless', 'Swamp'),
      card('Swamp', 'colorless', 'Swamp'),
      card('Forest', 'colorless', 'Forest'),
      card('Forest', 'colorless', 'Forest'),
      card('Necroblossom Snarl', 'colorless', 'Necroblossom Snarl'),
      card('Witherbloom Campus', 'colorless', 'Witherbloom Campus'),
    ],
  },
  prismari: {
    name: 'Prismari Tempo',
    description: 'Red/Blue — speed, card draw, portal tricks, row manipulation',
    cards: [
      card('Prismari Command', 'red', 'Prismari Command', 'prismari', ['red', 'blue']),
      card('Galazeth Prismari', 'red', 'Galazeth Prismari', 'prismari', ['red', 'blue']),
      card('Rootha, Mercurial Artist', 'red', 'Rootha, Mercurial Artist', 'prismari', ['red', 'blue']),
      card('Creative Outburst', 'red', 'Creative Outburst', 'prismari', ['red', 'blue']),
      card('Quandrix Command', 'blue', 'Quandrix Command', 'quandrix', ['green', 'blue']),
      card('Tanazir Quandrix', 'green', 'Tanazir Quandrix', 'quandrix', ['green', 'blue']),
      card('Expressive Iteration', 'red', 'Expressive Iteration'),
      card('Heated Debate', 'red', 'Heated Debate'),
      card('Pigment Storm', 'red', 'Pigment Storm'),
      card('Shivan Fire', 'red', 'Shivan Fire'),
      card('Ardent Dustspeaker', 'red', 'Ardent Dustspeaker'),
      card('Flame Channeler', 'red', 'Flame Channeler'),
      card('Sudden Breakthrough', 'red', 'Sudden Breakthrough'),
      card('Frost Trickster', 'blue', 'Frost Trickster'),
      card('Divide by Zero', 'blue', 'Divide by Zero'),
      card('Bury in Books', 'blue', 'Bury in Books'),
      card('Archmage Emeritus', 'blue', 'Archmage Emeritus'),
      card("Mentor's Guidance", 'blue', "Mentor's Guidance"),
      card('Vortex Runner', 'blue', 'Vortex Runner'),
      card('Waterfall Aerialist', 'blue', 'Waterfall Aerialist'),
      card('Pop Quiz', 'blue', 'Pop Quiz'),
      card('Curate', 'blue', 'Curate'),
      card('Ingenious Mastery', 'blue', 'Ingenious Mastery'),
      card('Symmetry Sage', 'blue', 'Symmetry Sage'),
      card('Island', 'colorless', 'Island'),
      card('Island', 'colorless', 'Island'),
      card('Mountain', 'colorless', 'Mountain'),
      card('Mountain', 'colorless', 'Mountain'),
      card('Frostboil Snarl', 'colorless', 'Frostboil Snarl'),
      card('Prismari Campus', 'colorless', 'Prismari Campus'),
    ],
  },
}
